users = [
  { username: "BeJeweled",
    email_address: "jewlz@jewlz.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Diamonds are Forevz",
    email_address: "diamonds@diamonds.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Ruby Tuesday",
    email_address: "roob@roob.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Opal's Opals",
    email_address: "opal@opal.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Hard Rock",
    email_address: "rock@rock.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Put a Ring on it",
    email_address: "ring@ring.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Crystal's Crystals",
    email_address: "crystal@crystal.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "The Bling Ring",
    email_address: "bling@ring.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Hot Rocks",
    email_address: "hot@rocks.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Treasure Trolls Gems",
    email_address: "troll@troll.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Jewel's Jewels",
    email_address: "jewel@jewel.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Shine Theory",
    email_address: "shine@theory.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Twinkles Gem Shop",
    email_address: "twinkle@twinkle.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Zanzabar Gems",
    email_address: "zanzabar@zanzabar.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Rings n Things",
    email_address: "rings@things.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Gems on Gems on Gems",
    email_address: "gems@gems.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Jem's Gems",
    email_address: "audrey@audrey.com",
    password: "123",
    password_confirmation: "123"
  },
  { username: "Rocky's Rock Shop",
    email_address: "rocky@rock.com",
    password: "123",
    password_confirmation: "123"
  }
]

orders = [
  { status: "pending",
    cc_name: "Hairy McNairy",
    email_address: "hair@hair.com",
    mailing_address: "123 Holly Lane",
    cc_number: 376254415526143,
    cc_exp: "11/16",
    cc_cvv: "563",
    zip: 45346,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "paid",
    cc_name: "Shea M Beedy",
    email_address: "shea@sh.com",
    mailing_address: "3423 Jello Street",
    cc_number: 349309788615040,
    cc_exp: "10/16",
    cc_cvv: "643",
    zip: 03664,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "cancelled",
    cc_name: "Larry B. Goode",
    email_address: "larbear@lar.com",
    mailing_address: "653 Octopus Ave",
    cc_number: 373196399237895,
    cc_exp: "11/17",
    cc_cvv: "909",
    zip: 98245,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "pending",
    cc_name: "Holly Juniper",
    email_address: "carebearz@gmail.com",
    mailing_address: "385 Woodstock Lane",
    cc_number: 378057410243640,
    cc_exp: "09/17",
    cc_cvv: "455",
    zip: 39653,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "paid",
    cc_name: "Amy Spaghetti",
    email_address: "meatballs@yahoo.com",
    mailing_address: "5333 Mockingbird Way",
    cc_number: 6011922064827826,
    cc_exp: "07/18",
    cc_cvv: "436",
    zip: 63578,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "cancelled",
    cc_name: "Henrietta Jane",
    email_address: "soccermom435@yahoo.com",
    mailing_address: "1000 15th Ave",
    cc_number: 4539570245560697,
    cc_exp: "11/17",
    cc_cvv: "355",
    zip: 46788,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "pending",
    cc_name: "Kay O'Hara",
    email_address: "cutiepootie@gmail.com",
    mailing_address: "45 South James St",
    cc_number: 4024007126415131,
    cc_exp: "11/19",
    cc_cvv: "087",
    zip: 35985,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "paid",
    cc_name: "Hollis O'Leary",
    email_address: "rainbowjoy344@hotmail.com",
    mailing_address: "22 Pine St",
    cc_number: 4929652131634238,
    cc_exp: "05/19",
    cc_cvv: "456",
    zip: 98357,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "cancelled",
    cc_name: "Andy Bahl",
    email_address: "batman635@hotmail.com",
    mailing_address: "5345 East Republican St",
    cc_number: 4556996862163598,
    cc_exp: "06/19",
    cc_cvv: "942",
    zip: 97446,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "pending",
    cc_name: "John Carlisle",
    email_address: "jcarl@gmail.com",
    mailing_address: "653 Gorge Way",
    cc_number: 5110538084994719,
    cc_exp: "06/18",
    cc_cvv: "674",
    zip: 19583,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "paid",
    cc_name: "George Schloeff",
    email_address: "yoohoo@yahoo.com",
    mailing_address: "74 West Highland Road",
    cc_number: 5303446871574552,
    cc_exp: "06/19",
    cc_cvv: "333",
    zip: 84573,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "cancelled",
    cc_name: "Mary Schleiblet",
    email_address: "ladydame@yahoo.com",
    mailing_address: "800 16th Ave",
    cc_number: 5303886871574552,
    cc_exp: "06/18",
    cc_cvv: "3334",
    zip: 84574,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "cancelled",
    cc_name: "Georgina Tartsey",
    email_address: "prettyinpink@yahoo.com",
    mailing_address: "79 West Highland Road",
    cc_number: 5403446871574553,
    cc_exp: "07/19",
    cc_cvv: "433",
    zip: 84583,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "paid",
    cc_name: "Jorge Delgotto",
    email_address: "ilovepeaches@yahoo.com",
    mailing_address: "800 Stinky Road",
    cc_number: 53034444471574552,
    cc_exp: "06/09",
    cc_cvv: "393",
    zip: 84573,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "pending",
    cc_name: "Alberta Albertson",
    email_address: "bigbassfisher@yahoo.com",
    mailing_address: "9 East Westland Road",
    cc_number: 53034468744435722,
    cc_exp: "06/20",
    cc_cvv: "338",
    zip: 44444,
    placed_at: rand(1.year.ago..Time.now)
  },
  { status: "cancelled",
    cc_name: "Al Sharkton",
    email_address: "tunafish35@yahoo.com",
    mailing_address: "39 Red Rock Road",
    cc_number: 5325283615453866,
    cc_exp: "04/16",
    cc_cvv: "467",
    zip: 79664,
    placed_at: rand(1.year.ago..Time.now)
  }
]

orderitems = [
  { product_id:33 , order_id: 1, quantity: 1 },
  { product_id: 32, order_id: 2, quantity: 2 },
  { product_id: 31, order_id: 3, quantity: 1 },
  { product_id: 30, order_id: 4, quantity: 1 },
  { product_id: 29, order_id: 5, quantity: 1 },
  { product_id: 28, order_id: 6, quantity: 1},
  { product_id: 27, order_id: 7, quantity: 2},
  { product_id: 25, order_id: 8, quantity: 1},
  { product_id: 24, order_id: 9, quantity: 1},
  { product_id: 23, order_id: 10, quantity: 1},
  { product_id: 22, order_id: 11, quantity: 2},
  { product_id: 21, order_id: 12, quantity: 1},
  { product_id: 19, order_id: 13, quantity: 2},
  { product_id: 18, order_id: 14, quantity: 3},
  { product_id: 17, order_id: 15, quantity: 1},
  { product_id: 44, order_id: 16, quantity: 1},
  { product_id: 16, order_id: 1, quantity: 1},
  { product_id: 15, order_id: 2, quantity: 2},
  { product_id: 14, order_id: 3, quantity: 3},
  { product_id: 13, order_id: 4, quantity: 2},
  { product_id: 12, order_id: 5, quantity: 1},
  { product_id: 11, order_id: 6, quantity: 1},
  { product_id: 10, order_id: 7, quantity: 1},
  { product_id: 43, order_id: 8, quantity: 1},
  { product_id: 42, order_id: 9, quantity: 1},
  { product_id: 41, order_id: 10, quantity: 1},
  { product_id: 40, order_id: 11, quantity: 1},
  { product_id: 39, order_id: 12, quantity: 1},
  { product_id:31 , order_id: 1, quantity: 1 },
  { product_id: 35, order_id: 2, quantity: 2 },
  { product_id: 30, order_id: 3, quantity: 1 },
  { product_id: 3, order_id: 4, quantity: 1 },
  { product_id: 2, order_id: 5, quantity: 1 },
  { product_id: 1, order_id: 6, quantity: 1},
  { product_id: 5, order_id: 7, quantity: 2},
  { product_id: 4, order_id: 8, quantity: 1},
  { product_id: 6, order_id: 9, quantity: 1},
  { product_id: 7, order_id: 10, quantity: 1},
  { product_id: 8, order_id: 11, quantity: 2},
  { product_id: 9, order_id: 12, quantity: 1},
  { product_id: 10, order_id: 13, quantity: 2},
  { product_id: 11, order_id: 14, quantity: 3},
  { product_id: 50, order_id: 15, quantity: 1},
  { product_id: 45, order_id: 16, quantity: 1},
  { product_id: 17, order_id: 1, quantity: 1},
  { product_id: 1, order_id: 2, quantity: 2},
  { product_id: 12, order_id: 3, quantity: 3},
  { product_id: 17, order_id: 4, quantity: 2},
  { product_id: 19, order_id: 5, quantity: 1},
  { product_id: 25, order_id: 6, quantity: 1},
  { product_id: 52, order_id: 7, quantity: 1},
  { product_id: 50, order_id: 8, quantity: 1},
  { product_id: 49, order_id: 9, quantity: 1},
  { product_id: 26, order_id: 10, quantity: 1},
  { product_id: 23, order_id: 11, quantity: 1},
  { product_id: 3, order_id: 12, quantity: 1},
  { product_id: 13, order_id: 2, quantity: 2},
  { product_id: 1, order_id: 3, quantity: 3},
  { product_id: 7, order_id: 4, quantity: 2},
  { product_id: 29, order_id: 5, quantity: 1},
  { product_id: 15, order_id: 6, quantity: 1},
  { product_id: 43, order_id: 7, quantity: 1},
  { product_id: 51, order_id: 8, quantity: 1},
  { product_id: 4, order_id: 9, quantity: 1},
  { product_id: 6, order_id: 10, quantity: 1},
  { product_id: 13, order_id: 11, quantity: 1},
  { product_id: 9, order_id: 12, quantity: 1}
]

reviews = [
  { rating: 1, product_id: 1, body: "Hideous. disappointed. returning it."},
  { rating: 5, product_id: 2, body: "My daughter LOVED it!"},
  { rating: 4, product_id: 3, body: "Not as shiny as in the picture, but still nice."},
  { rating: 3, product_id: 4, body: "Pretty high quality gem."},
  { rating: 1, product_id: 5, body: "Looks NOTHING like the photo. Awful."},
  { rating: 5, product_id: 6, body: "So dazzling! Love."},
  { rating: 3, product_id: 7, body: "Not worth the money, but a good product."},
  { rating: 4, product_id: 8, body: "Cuuuuute."},
  { rating: 5, product_id: 9, body: "My fiancee proposed to me with this! I love it!!"},
  { rating: 1, product_id: 10, body: "Broke a day after arriving."},
  { rating: 4, product_id: 11, body: "Looks a little cheaper than in the photo, but overall I like it."},
  { rating: 3, product_id: 12, body: "Not really my style. Kind of tacky."},
  { rating: 5, product_id: 13, body: "I'll be buying another one for my husband!!"},
  { rating: 5, product_id: 23, body: "Getting this as a holiday gift for everyone I know!"},
  { rating: 5, product_id: 24, body: "Dazzling. Just dazzling."},
  { rating: 5, product_id: 25, body: "Absolutely stunning."},
  { rating: 2, product_id: 26, body: "Honestly, not very flattering."},
  { rating: 5, product_id: 27, body: "My wife cried when she opened it. Out of joy!"},
  { rating: 2, product_id: 28, body: "Not sure what they were going for with this cut of gem..."},
  { rating: 1, product_id: 29, body: "It fell apart a week later."},
  { rating: 5, product_id: 30, body: "Absolutely worth the money!"},
  { rating: 4, product_id: 40, body: "Not the best cut, but a decent bargain."},
  { rating: 3, product_id: 50, body: "It's okay. I've seen more impressive."},
  { rating: 1, product_id: 41, body: "Ugh. Waaaay too shiny, it hurts my eyes."},
  { rating: 2, product_id: 42, body: "Gave me a headache from looking at it."},
  { rating: 5, product_id: 43, body: "My aunt looooooved it!"},
  { rating: 4, product_id: 44, body: "Looks VERY nice against my skin."},
  { rating: 5, product_id: 45, body: "oh my god...stunning gem."},
  { rating: 1, product_id: 46, body: "gross."},
  { rating: 2, product_id: 47, body: "Who would WANT this? ripoff."},
  { rating: 5, product_id: 48, body: "I'll be back for another when I can afford it!"},
  { rating: 4, product_id: 49, body: "Quality product- well chiseled."},
  { rating: 4, product_id: 50, body: "I wish it were bigger, but it's pretty cool."},
  { rating: 5, product_id: 1, body: "Gorgeous stone!"},
  { rating: 5, product_id: 10, body: "This is EXACTLY what I was looking for for my anniversary."},
  { rating: 2, product_id: 11, body: "Smaller than it looks in the photo."},
  { rating: 1, product_id: 12, body: "Buyer beware- it's REALLY cheap."},
  { rating: 2, product_id: 13, body: "Scratched my child while he was playing with it."},
  { rating: 1, product_id: 14, body: "NOT pet safe. My cat ate it and I had to take him to the vet."},
  { rating: 5, product_id: 15, body: "Makes me feel young again!"},
  { rating: 4, product_id: 16, body: "I want to bejewel my whole body with this!"},
  { rating: 2, product_id: 17, body: "NOT child safe!! My toddler ate three of these."},
  { rating: 1, product_id: 18, body: "It gave me a horrible allergic reaction. NOT for people with sensitive skin."},
  { rating: 2, product_id: 19, body: "Lost its luster after a short period of time."},
  { rating: 3, product_id: 20, body: "I went to have it shined and it turned green. But before that it was nice."},
  { rating: 4, product_id: 21, body: "Reeeally pretty jewel, but a little pricey for my taste."},
  { rating: 5, product_id: 22, body: "I'm getting married because of this bad boy!"},
  { rating: 1, product_id: 23, body: "My sister was wearing it and she ended up having to go to the hospital. Do NOT recommend."},
  { rating: 2, product_id: 24, body: "Not my favorite from this vendor. I think they are using a new manufacturer and the quality has dropped in recent years."},
  { rating: 5, product_id: 25, body: "I'm on my fifth marriage- this lil puppy charms them into saying yes every time."},
  { rating: 4, product_id: 26, body: "Classy. Classic. Timeless"},
  { rating: 4, product_id: 40, body: "WILL take your breath away. I love it."},
  { rating: 5, product_id: 41, body: "Timeless elegance!"},
  { rating: 5, product_id: 42, body: "My husband and I each got matching ones- they're so cute side by side!"},
  { rating: 2, product_id: 43, body: "Turned green after water got on it."},
  { rating: 5, product_id: 44, body: "hideous. disappointed. returning it."},
  { rating: 1, product_id: 45, body: "I LITERALLY think this gem has a curse on it, because bad things have been happening to me all year."},
  { rating: 1, product_id: 12, body: "I fell down the stairs after I put it on- I think it's cursed."},
  { rating: 5, product_id: 3, body: "Makes me so happy when I see it in my jewelry box every morning."},
  { rating: 5, product_id: 4, body: "My daughter wears this every day!"}
]

products = [
  # Emerald
  {retired: false, name:"Emerald Sword", price: 2040 , user_id: "1", stock: "2" , photo_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSdu1XTO5gfUbPLLseSkv2QgYSoofnZ6tx3Yt3BXo2OQUMakGMQ", description: "Let this delightful emerald sword help you thwack your way through the world." },
  {retired: false, name: "Pure Emerald Block", price: 6500, user_id: "12", stock: "25", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSo-egwLeTw02paY3aP79TTmx3FzJIKZqxlVDLcpAVwQ858cZdq_g", description: "Use this lovely emerald block to build all the things."},
  {name: "Fancy Pantsy Necklace", price: 600, user_id: "14", stock: "22", photo_url: "http://www.faberge.com/images/thumbs/0006090_690.jpeg", description: "Look the best at your next fancy party."},
  {name: "Gaudy Is For Lovers", price: 800, user_id: "4", stock: "1", photo_url: "http://i.ebayimg.com/00/s/MzAwWDMwMA==/z/ZiYAAOSwnDZUAAOK/$_35.JPG?set_id=2", description: "Bedeck your hands with this one-of-a-kind glory."},
  # Ruby
  {name: "Ruby Sword", price: 7868, user_id: "2", stock: "5", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS7u0rM40peU5eoDCl7PCmyMpsg7c1iqco_dzvQn_1c_ah8L298hGXF9AU", description: "You won't even be able to see the blood."},
  {retired: false, name: "Blood Red Shovel", price: 666, user_id: "1", stock: "5", photo_url: "http://vignette1.wikia.nocookie.net/minecraftfanfictions/images/5/5e/Ruby_shovel.png/revision/latest?cb=20120803133632", description: "Bury the bodies of your enemies in style."},
  {name: "One Ring to Rule Them All", price: 4254, user_id: "6", stock: "4", photo_url: "http://verdura.blob.core.windows.net/images/products/0578255bca9e4a539026537b0ec50fe7/large", description: "Just try to find a matching outfit for this one... "},
  {name: "Radical Ruby Ring", price: 5432, user_id: "6", stock: "55", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRU5kK3fdZX3VXVQjR84Skk27lVwBjDV5NJnmmhSexK1CJqi8WhaQ", description: "It's a ring. With a ruby in it. "},
  {retired: true, name: "Raw Ruby Rock", price: 343, user_id: "15", stock: "3", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTboRwcl_mhVPNT7hW03VNdENxn0bRXCto_dPuGzJNZfGTQGqUO", description: "I guess calling it a rock doesn't make you want to buy it."},
  {name: "Funny Looking Ruby", price: 453, user_id: "16", stock: "456", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjOjxJma6TgDA-WOw2z1w0lZ0Yvw7epBR_Uy_IRjhfQoxQUypH", description: "It's synthetic, what did you expect?"},
  {name: "Not Craisins", price: 45, user_id: "16", stock: "32", photo_url: "https://static.auctionmate.io/gr/uploads/images/255000-259999/257107/257107_1328612158.jpg", description: "Don't eat these rubies, they'll hurt your teeth."},
  {name: "Pulsing Pendant", price: 433, user_id: "11", stock: "34", photo_url: "http://www.raritetantique.com/img/products/Jewelry/Sets/Raw%20Ruby%20Set%20ring%20pendant/Vintage%20Raw%20Ruby%20Diamond%2014K%20Gold%20Ring%20Pendant%20Set%20(11).jpg", description: "Like gold fingers clenching your beating heart. It'll look great with your cheekbones."},
  {retired: true, name: "Ruby Necklace", price: 453, user_id: "3", stock: "45", photo_url: "http://www.jared.com/images/products/1333/133361004_MV_ZM_JAR.jpg", description: "It'a necklace. You put it around your neck."},
  {name: "Red Crown", price: 5353, user_id: "8", stock: "33", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4fLrTjmOCHPy5RdAgELSXIyw5m8IX5hHSfZuqrxqG9-Wseh8j", description: "Because you're a queen."},
  {name: "Spider Heart", price: 4532, user_id: "6", stock: "2", photo_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuxZHOkKmRQTBVQ8VUnrrGu-xMtl4E8--JKB3w34ZR29zq2926", description: "I put a spell on you, and now you're miiine... "},
  # Diamond
  {name: "Geometry Like Woah", price: 5645, user_id: "2", stock: "1", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDeCvOq-lfd-xau5kCj_RZ5WOD1wldXJybYd9abKVYwZKaGAay", description: "I drew this just for you."},
  {name: "Geometry 2", price: 5435, user_id: "2", stock: "1", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSEgpQiG4wS992NcEjjLVfhzBCj5pmqYLFDo4XDEQJx69DmC_O5vA", description: "Another angle, especially for you."},
  {name: "Geometry 3", price: 5354, user_id: "2", stock: "1", photo_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcShLGH5v6h395Bd7I4Kvro4p1uNEpzcb1Ze8eZOXiXL_wMP8f6N8A", description: "In case you wanted something that pops. I drew it for you. Love me?"},
  {retired: true, name: "Fancy Pants Set", price: 5542, user_id: "4", stock: "4", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtiizC6M9GRTugFfzo0mYBrM1oPk-kCKzKc4EDz0ZATCdtExRXOQ", description: "To show how much you care."},
  {name: "Every Kiss Begins With A Letter of the Alphabet", price: 43, user_id: "5", stock: "32", photo_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTDaj_MIMbt2FZIpf5a23889fpxQe0KX7Zv2lEIhHLCgh6pdH8NIw", description: "Risk: Swallowing Hazard. Keep Away From Small Children."},
  # Azurite
  {name: "Ocean Pendant", price: 452, user_id: "4", stock: "4", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRULoT20bJYqQe9ZG0ZaWwNxohZs1CNTcy6gn4qbmJKIB5-aoSULA", description: "Hold the ocean on your chest. On your chest? Somewhere. Bring a towel."},
  {name: "Square Pendant", price: 3642, user_id: "5", stock: "4", photo_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSqcsrEC9WSg7rZ_SDfMVqdYCYROTDuyCzkPM4ibA6WXnsS3DBoSQ", description: "Disclaimer: This is NOT a lava lamp."},
  {name: "Earth Day Earrings", price: 5223, user_id: "5", stock: "2", photo_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSCYoPOKaAS85w9NPGquyeS3i3EuDwOcnlUcMOud1j5uyoseRTshg", description: "Who needs shoulders when you've got ears?"},
  {name: "Rad Pretty Rock", price: 4343, user_id: "15", stock: "88", photo_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQGYDxlpcTX59vlgTzMDw0f8R6scoAi0fCImFOUSa7mYze-s4V9-g", description: "I dug it up myself."},
  {name: "Radioactive Earrings", price: 5353, user_id: "13", stock: "7", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq9o_V-qgosXZDGZ09vFmRn662HHEdtb4J_tO3-6kzKwWIw2w", description: "Just kidding. I swear.."},
# Saphhire
  {name: "Floral Pendant", price: 5434, user_id: "3", stock: "6", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQCr5oLFJAVGA_Yk6lO9V9_2vVxObHr8eiq4FatLm4NUK9Q8qGy", description: "It's flowery and stuff."},
  {name: "Sapphire Studs", price: 3522, user_id: "7", stock: "5", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAIXAGZ305zjSNF5G5RUEsqTlJqhZD7HI529vAHdBIBIya3olG", description: "Make your ears have more blue."},
  {name: "Swan Pendant", price: 5344, user_id: "8", stock: "43", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT48T18ftz5Ob4bEskZVWC0UlEfxCp7D6cS5UuQs1_KSDZXBa4-", description: "You can see it if you look really hard."},
  {name: "Sails!", price: 455, user_id: "12", stock: "4325", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTojfeqUe8S2DR6CdpHIZ6udS3UPwzpN4D56W7OaaY_7zSlu4vD4Q", description: "Sail away, my dear."},
  {name: "A Three-fer", price: 3235, user_id: "4", stock: "34", photo_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRXSnmM4i_3B1_I9K9CQ1M14jV5gn_GosC613w75JpMFv_x_OFESw", description: "Three for the price of three!"},
# Quartz
  {name: "I Carry your Heart", price: 3455, user_id: "11", stock: "4", photo_url: "http://i.ebayimg.com/00/s/MzAwWDMwMA==/z/n~EAAOSwVFlT~-CI/$_35.JPG?set_id=2", description: "... I carry it in my heart"},
  {name: "Moon Ring", price: 2356, user_id: "13", stock: "2", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT8WoXh7XoD6nrqUMQDu-lNAcfSXauMNz0bzSPBIKJafWQCKPb_", description: "Moon, not mood."},
  {name: "Studly Studs", price: 425, user_id: "13", stock: "13", photo_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRugLdkSKwolyJaIW36Ss2HfgGRKB-eJxJJJsoWEQjTTlGSqZws", description: "Studly. Get it? Heh."},
  {name: "Stabby Rose", price: 4325, user_id: "18", stock: "552", photo_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRQXU_7xJiy0xjdnDJcowY5ZUZcjyqVYaup9wk7mI-JxTSB9fPc", description: "Fashion AND function."},
  {retired: true, name: "Purdy Pink Rock", price: 4535, user_id: "", stock: "11", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTDoDZLerT9aF8YAccRznJvyuFMpymri0e_Rlb6JnEj_yTgkHGIWw", description: "it's worth it, I swear."},
  {name: "A Thing", price: 3456, user_id: "16", stock: "3", photo_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSICTPb__nMJZfrKRpQPChCru24VOXtTYhKIX3wmo7Ie-xrR9cTkQ", description: "Would be a great paperweight."},
  {name: "Clear Rock", price: 542, user_id: "12", stock: "3", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcScL2Au5edYrPpNNddkuNk20OmxspUfIqDmLyTg8P_5cI6nj0k7Fg", description: "Look at those crsip edges."},
  {name: "Prettier Pink Rock", price: 4356, user_id: "18", stock: "4", photo_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQeBacGzU61npNBaFDxetu2v9n_dQw8XJa9_Z08eAfEGkLXqOFL", description: "Throw it at someone if you need."},
# Amethyst
  {name: "Functional Paperweight", price: 3225, user_id: "18", stock: "3", photo_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR9ZdYBT9RPsNPtRq4Nv3s57KpkrPZUM54lBUmzVGH-KSMAbILPIQ", description: "Toss at your enemies, or pet for comfort."},
  {name: "Egg on Stand", price: 3534, user_id: "8", stock: "4", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-UyhnUBMJ8rsUhrhY7ntq688MTCzd7U_wjNq5Ezmzu-dIKqcKQA", description: "Because of course you need an inedbile egg. The gold stand is free!"},
  {name: "Flat Geode Thing", price: 4245, user_id: "9", stock: "4", photo_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQa-wHb6aNhafTkibBQr1j1OtXecS2q_acji6E0fWVeSR5mWecxxQ", description: "Not a piece of sandwich bread."},
  {name: "Amethyst Sword", price: 5425, user_id: "10", stock: "2", photo_url: "http://www.orespawn.com/uploads/2/5/3/5/25358181/2043216_orig.png", description: "Thwack thine enemies."},
  {name: "Heart on Her Finger", price: 542, user_id: "17", stock: "3", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDf9QsBbInlxPl_fXZSSU0E46zh2lk5nm71nQxeMvi8RhzUUpX", description: "Because sleeves are for chumps."},
  {retired: true, name: "Flutter-by Butterfly", price: 432, user_id: "7", stock: "5", photo_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSj21LIRFpwLJ717Nl3NFLq001uUnyW5v2Yr_czZ6B4kjAtYUK0", description: "Disclaimer: It doesn't really fly."},
# Tourmaline
  {name: "Jolly Rancher", price: 4323, user_id: "9", stock: "3", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRpAO3vwZgK_Ei7brkJLsYtLkeg7O7BH4-kJiieCFtD-D0M_WiO", description: "Not a candy necklace."},
  {name: "Jormungand", price: 5435, user_id: "10", stock: "1", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQKc_QG74TfTtFvS7yzv4IjMK_bOzezHLahSIE_Dfw0j3DNZ-8hww", description: "..."},
  {name: "Gem Bracelet", price: 4324, user_id: "17", stock: "2", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCe93wq6WsmHnNE8tZBpfebGqZb3xgR94Te0uwMLH2H9M-RfUwRg", description: "Can't pick one color? Get 'em all!"},
  {name: "Some Earrings", price: 4352, user_id: "9", stock: "2", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRpA5O0n89dJERD3xRNQ8VJ2bpgO0uMvlqp4ihw8Yt1Pb8TIhbQEw", description: "Make sure their ears are pierced first."},
  {name: "Radioactive Butterfly", price: 4522, user_id: "14", stock: "4", photo_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTfeTfBprAtSAx30yerUy-Ps-DEHGiPMjgYxRfL126tlFE3lqAThw", description: "Not proven to cause cancer in humans."},
  {retired: true, name: "Inedible Watermelon", price: 3252, user_id: "7", stock: "2", photo_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQuR4zzXZ08xSF44BfkuKjyEMV53JSEppiysKf-L-YokMv2wVwdcQ", description: "Disclaimer: not a ring-pop."},

# Turquoise
  {name: "Turquoise Set", price: 342, user_id: "17", stock: "3", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAT_lQaYED2EAswqwQ7LAfUrPTOcyvRathjpdNNoEv4VLfl6ty", description: "No need to mix and match."},
  {name: "Probably Fake Turquoise Rings", price: 544, user_id: "10", stock: "6765", photo_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQoGPq0oTIxG8tXbaUH9YNqfZQWjS4N9oqGVES-iGt7-UHphsiL", description: "But you look cool until your fingers are green."},
  {name: "T-Chainz", price: 3255, user_id: "14", stock: "23", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLXniy8gk5MCCGIrDXINEaYRffW0UkVmN1-sOAUoCC1LYNghI5ug", description: "Cuter than handcuffs."},
  {name: "T-Earth", price: 4325, user_id: "15", stock: "2", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlkA8Z3x1WgIFcMxPAYnPB0ViPmYIQPyDyFUAQYlT3vqvvp6ck9w", description: "I actually like this one."},
]

categories = [
  {name: "Emerald"},
  {name: "Ruby"},
  {name: "Diamond"},
  {name: "Sapphire"},
  {name: "Quartz"},
  {name: "Amethyst"},
  {name: "Tourmaline"},
  {name: "Turquoise"},
]

category_products = [
  {category_id: "1", product_id: "1"},
  {category_id: "1", product_id: "2"},
  {category_id: "1", product_id: "3"},
  {category_id: "1", product_id: "4"},
  {category_id: "2", product_id: "5"},
  {category_id: "2", product_id: "6"},
  {category_id: "2", product_id: "7"},
  {category_id: "2", product_id: "8"},
  {category_id: "2", product_id: "9"},
  {category_id: "2", product_id: "10"},
  {category_id: "2", product_id: "11"},
  {category_id: "2", product_id: "12"},
  {category_id: "2", product_id: "13"},
  {category_id: "2", product_id: "14"},
  {category_id: "2", product_id: "15"},
  {category_id: "3", product_id: "16"},
  {category_id: "3", product_id: "17"},
  {category_id: "3", product_id: "18"},
  {category_id: "3", product_id: "19"},
  {category_id: "3", product_id: "20"},
  {category_id: "11", product_id: "21"},
  {category_id: "11", product_id: "22"},
  {category_id: "11", product_id: "23"},
  {category_id: "11", product_id: "24"},
  {category_id: "11", product_id: "25"},
  {category_id: "4", product_id: "26"},
  {category_id: "4", product_id: "27"},
  {category_id: "4", product_id: "28"},
  {category_id: "4", product_id: "29"},
  {category_id: "4", product_id: "30"},
  {category_id: "5", product_id: "31"},
  {category_id: "5", product_id: "32"},
  {category_id: "5", product_id: "33"},
  {category_id: "5", product_id: "34"},
  {category_id: "5", product_id: "35"},
  {category_id: "5", product_id: "36"},
  {category_id: "5", product_id: "37"},
  {category_id: "5", product_id: "38"},
  {category_id: "6", product_id: "39"},
  {category_id: "6", product_id: "40"},
  {category_id: "6", product_id: "41"},
  {category_id: "6", product_id: "42"},
  {category_id: "6", product_id: "43"},
  {category_id: "6", product_id: "44"},
  {category_id: "7", product_id: "45"},
  {category_id: "7", product_id: "46"},
  {category_id: "7", product_id: "47"},
  {category_id: "7", product_id: "48"},
  {category_id: "7", product_id: "49"},
  {category_id: "7", product_id: "50"},
  {category_id: "8", product_id: "51"},
  {category_id: "8", product_id: "52"},
  {category_id: "8", product_id: "53"},
  {category_id: "8", product_id: "54"}
]

products.each do |p|
  prod = Product.new(p)
  prod.save(validate: false)
end

categories.each do |c|
  cat = Category.new(c)
  cat.save(validate: false)
end

orderitems.each do |o|
  orditem = Orderitem.new(o)
  orditem.save(validate: false)
end

users.each do |u|
  user = User.new(u)
  user.save(validate: false)
end

orders.each do |o|
  order = Order.new(o)
  order.save(validate: false)
end

reviews.each do |r|
  review = Review.new(r)
  review.save(validate: false)
end

category_products.each do |c|
  catprod = CategoriesProduct.new(c)
  catprod.save(validate: false)
end
